### ISSUE TITLE
Missing spaces before and after links

### ISSUE THREAD

**Issue by Weissheiten** [TYPO3-Documentation/typo3-writing-guide#2]
The rendered version is missing spaces before and after links on all entries.

Example
Email your suggestions, feedback, examples, or other ideas **totypo3writersguide@openstrategypartners.com.**

should be
Email your suggestions, feedback, examples, or other ideas to **typo3writersguide@openstrategypartners.com.**

**Comment by DavidBruchmann** [comment]
Thanks @Weissheiten, can you link an example page where this is relevant?

**Comment by Weissheiten** [comment]
Sure. It is currently the case for the whole document, so you can virtually take any page, for example: https://docs.typo3.org/m/typo3/writing-guide/main/en-us/about-this-guide.html from which the example text I quoted in the original issue originates.
